#!/usr/bin/env bash

# starship
sh -c "$(curl -fsSL https://starship.rs/install.sh)"

# download oh-my-zsh and plugins

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting -q
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions -q
git clone https://github.com/hlissner/zsh-autopair ~/.zsh-autopair -q
git clone "https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv.git" "$ZSH_CUSTOM/plugins/autoswitch_virtualenv"
rm -rf ~/.zshrc

# set dotfiles
cd ~/.dotfiles
STOW_FOLDERS="git,scripts,kitty,i3,zsh,tmux,wallpapers"

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done

ln -s ~/.config/nvim ~/.vim
ln -s ~/.config/nvim/init.vim ~/.vimrc

echo "Install Sucefull"
