#!/usr/bin/env bash

# setup vim
git clone https://github.com/neovim/neovim -q ~/.cache/neovim --depth=1

# download oh-my-zsh and plugins

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting -q
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions -q
git clone https://github.com/hlissner/zsh-autopair ~/.zsh-autopair -q
rm -rf ~/.zshrc

# set dotfiles
cd ~/.dotfiles
STOW_FOLDERS="git,scripts,kitty,i3,zsh,tmux"

# install ZorinOS Theme

mkdir "/tmp/themes/{gtk,icon}"
git clone https://github.com/ZorinOS/zorin-desktop-themes /tmp/themes/gtk -q
git clone https://github.com/ZorinOS/zorin-icon-themes /tmp/themes/icon -q
mv /tmp/themes/gtk/* ~/.themes
mv /tmp/themes/icon/* ~/.icons

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done

ln -s ~/.config/nvim ~/.vim
ln -s ~/.config/nvim/init.vim ~/.vimrc

echo "Install Sucefull"
